// <auto-generated />
namespace VRbit.Agendamentos.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class usersadicionais : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usersadicionais));
        
        string IMigrationMetadata.Id
        {
            get { return "201902031956506_usersadicionais"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
